---
- name: Mac custom
  hosts: all
  connection: local

  vars_files:
    - config.yml
    - config.local.yml

  roles:

    # --------------------------------------------------------------------------

    # Requiring roles
    # ---------------

    # The roles below are included in requirements.yml.
    # "Required" roles are downloaded from remote sources.

    # Ansible Galaxy docs:
    # http://docs.ansible.com/ansible/latest/galaxy.html

    # --------------------------------------------------------------------------

    # Using tags
    # ----------

    # Each role has a unique & descriptive tag so that specific roles can be
    # run via the `ansible-playbook` command.

    # Ansible tags docs:
    # http://docs.ansible.com/ansible/latest/playbooks_tags.html

    # --------------------------------------------------------------------------

    # Basic role example.
    - { role: danbohea.spelling, tags: ["spelling"] }

    # Passing a variable to a role.
    - { role: danbohea.cask-app, cask_app_name: "muzzle", tags: ["muzzle"] }

    # Using the "always" tag on a role to ensure it always runs,
    # no matter what tags you instructed Ansible to run.
    - { role: danbohea.dock-items, tags: ["dock_items","always"] }

    # --------------------------------------------------------------------------

    #  More info on the example roles used here:

    # https://github.com/danbohea/ansible-role-spelling
    # https://github.com/danbohea/ansible-role-cask-app
    # https://github.com/danbohea/ansible-role-dock-items

    # You can find further compatible roles via the Ansible Galaxy website.
    # Here's a good starting point:

    # https://galaxy.ansible.com/list#/roles?page=1&page_size=20&users=danbohea&autocomplete=macsible&order=name,username

    # --------------------------------------------------------------------------

  post_tasks:

    - debug:
        msg: "Some changes may not take effect until you've restarted your Mac."
      tags: always
